version: "3.8"

services:
  backend:
    build: ./Model
    container_name: fastapi_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./UI
    container_name: nginx_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
